/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./deepin-service-manager/src/demo/plugin-qt/demo2/org.deepin.service.demo2b.xml -a ./deepin-service-manager/toolGenerate/qdbusxml2cpp/org.deepin.service.demo2bAdaptor -i ./deepin-service-manager/toolGenerate/qdbusxml2cpp/org.deepin.service.demo2b.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_SERVICE_DEMO2BADAPTOR_H
#define ORG_DEEPIN_SERVICE_DEMO2BADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./deepin-service-manager/toolGenerate/qdbusxml2cpp/org.deepin.service.demo2b.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.service.demo2b
 */
class Demo2bAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.service.demo2b")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.service.demo2b\">\n"
"    <method name=\"Hello\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"Register\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"result\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"result2\"/>\n"
"    </method>\n"
"    <method name=\"SetArea\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"in\" type=\"a(iiii)\" name=\"area\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"result\"/>\n"
"      <annotation value=\"AreaList\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </method>\n"
"    <signal name=\"Tick\"/>\n"
"    <signal name=\"AreaTestSig\">\n"
"      <arg type=\"s\" name=\"id\"/>\n"
"      <arg type=\"a(iiii)\" name=\"aaa\"/>\n"
"      <annotation value=\"AreaList\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </signal>\n"
"    <property access=\"read\" type=\"b\" name=\"Locked\"/>\n"
"    <property access=\"readwrite\" type=\"u\" name=\"Age\">\n"
"      <annotation value=\"const\" name=\"org.freedesktop.DBus.Property.EmitsChangedSignal\"/>\n"
"    </property>\n"
"    <property access=\"readwrite\" type=\"s\" name=\"msg\"/>\n"
"    <property access=\"readwrite\" type=\"a(iiii)\" name=\"areas\">\n"
"      <annotation value=\"AreaList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"  </interface>\n"
        "")
public:
    Demo2bAdaptor(QObject *parent);
    virtual ~Demo2bAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uint Age READ age WRITE setAge)
    uint age() const;
    void setAge(uint value);

    Q_PROPERTY(bool Locked READ locked)
    bool locked() const;

    Q_PROPERTY(AreaList areas READ areas WRITE setAreas)
    AreaList areas() const;
    void setAreas(AreaList value);

    Q_PROPERTY(QString msg READ msg WRITE setMsg)
    QString msg() const;
    void setMsg(const QString &value);

public Q_SLOTS: // METHODS
    QString Hello();
    bool Register(const QString &id, QString &result2);
    bool SetArea(const QString &id, AreaList area);
Q_SIGNALS: // SIGNALS
    void AreaTestSig(const QString &id, AreaList aaa);
    void Tick();
};

#endif
