/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./deepin-service-manager/src/demo/plugin-qt/demo2/org.deepin.service.demo2a.xml -a ./deepin-service-manager/toolGenerate/qdbusxml2cpp/org.deepin.service.demo2aAdaptor -i ./deepin-service-manager/toolGenerate/qdbusxml2cpp/org.deepin.service.demo2a.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_DEEPIN_SERVICE_DEMO2AADAPTOR_H
#define ORG_DEEPIN_SERVICE_DEMO2AADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./deepin-service-manager/toolGenerate/qdbusxml2cpp/org.deepin.service.demo2a.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.deepin.service.demo2a
 */
class Demo2aAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.deepin.service.demo2a")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.deepin.service.demo2a\">\n"
"    <method name=\"Hello\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"Register\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"result\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"result2\"/>\n"
"    </method>\n"
"    <property access=\"readwrite\" type=\"s\" name=\"msg\"/>\n"
"  </interface>\n"
        "")
public:
    Demo2aAdaptor(QObject *parent);
    virtual ~Demo2aAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString msg READ msg WRITE setMsg)
    QString msg() const;
    void setMsg(const QString &value);

public Q_SLOTS: // METHODS
    QString Hello();
    bool Register(const QString &id, QString &result2);
Q_SIGNALS: // SIGNALS
};

#endif
